# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2010-2015 Intel Corporation

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_LIBRTE_MLX5_REGEX_PMD) += mlx5

include $(RTE_SDK)/mk/rte.subdir.mk
